### ISSUE TITLE
Connection refused or loads forever

### ISSUE THREAD

**Issue by xeijin** [fabiobeoni/adapt-authoring-standalone#2]
Hardware: MacBook Pro 2017
OS: Windows 10
Browser: Chrome 62.0.3202.75

Downloaded zip, unzipped to C:/adapt.

Open start.exe, click start, browser window opens, seems to try to load then presented with a 'Connection Refused'. I later tried again by browsing to 'localhost:5000' but it seems to be loading forever (still loading 5 mins later at the time of writing). I don't think my hardware qualifies as 'slow' so feels like something else is going wrong potentially.

Have disabled Windows Firewall but still get the same result.

**Comment by xeijin** [comment]
I let it continue loading, I now get the following in Chrome:

> This page isn’t working
> 
> localhost didn’t send any data.
> ERR_EMPTY_RESPONSE

But loading circle of the tab still going...

**Comment by fabiobeoni** [comment]
Thanks for sharing.

The run procedure includes:
1. run of mongodb,
2. add to your PATH the dir "C:\adapt\node"
3. run of nodejs and adapt app
4. run of browser on localhost:5000

Please answer the following questions:
1. Can you confirm that the mongodb process and nodejs process are working after you click on "Start"? 
2. Do you have admin rights on the PC?
3. Is the C:\adapt dir fully writable?

Thanks!

**Comment by fabiobeoni** [comment]
Closing due to missing answer.
